name: New Issue
on:
  issues:
    types: [opened]
jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details
        run: |
          echo "Issue details: ${{ toJSON(github.event.issue) }}"
